name: build-and-deploy-to-winServer
on:
  push:
    branches:
      - main
jobs:
  # To build the project
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
         name: application
         path: /home/runner/work/reactAppOnWinServer/build/*
  deploy: 
    needs: Build
    runs-on: self-hosted
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
       name: application
       # Destination path
       path: C:\inetpub\wwwroot
 
